### ISSUE TITLE
Call to a member function query() on string

### ISSUE THREAD

**Issue by yvtang** [easy-swoole/fast-db#6]
执行模型创建脚本时报错
Call to a member function query() on string
Stack trace:
#0 /home/yvtang/easyswoole/vendor/easyswoole/fast-db/src/Commands/GenModelAction.php(43): EasySwoole\FastDb\Commands\GenModelAction->getColumnTypeListing()
#1 [internal function]: EasySwoole\FastDb\Commands\GenModelAction->EasySwoole\FastDb\Commands\{closure}()
#2 {main}
  thrown in /home/yvtang/easyswoole/vendor/easyswoole/fast-db/src/Commands/GenModelAction.php on line 106

**Comment by XueSiLf** [comment]
已修复，可查看：https://github.com/easy-swoole/fast-db/pull/7

**Comment by XueSiLf** [comment]
已修复，可查看：https://github.com/easy-swoole/fast-db/pull/7
