### ISSUE TITLE
执行gen命令，生成model文件丢失主键字段

### ISSUE THREAD

**Issue by 454592673** [easy-swoole/fast-db#9]
![image](https://github.com/easy-swoole/fast-db/assets/22283930/7d007c30-ca7e-466f-95c5-54043c804149)
![image](https://github.com/easy-swoole/fast-db/assets/22283930/a6bfc0d3-bd48-4762-8dab-58df45fd44af)
![image](https://github.com/easy-swoole/fast-db/assets/22283930/29694528-c5cd-47b0-9d32-a6f9e792770f)

**Comment by XueSiLf** [comment]
好的，稍后就修复。

**Comment by XueSiLf** [comment]
> ![image](https://private-user-images.githubusercontent.com/22283930/343681185-7d007c30-ca7e-466f-95c5-54043c804149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjAwOTUsIm5iZiI6MTcyMDA1OTc5NSwicGF0aCI6Ii8yMjI4MzkzMC8zNDM2ODExODUtN2QwMDdjMzAtY2E3ZS00NjZmLTk1YzUtNTQwNDNjODA0MTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMTE4OTg5NmYyMWUxZDU3ZDkxMDM3NmNiZGVmMTExZTU0MWVjOWE3OTMxZmQwNzFmMzIzYTJhYTIxOTg1ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XXPgbWxAMR2n7D7ZCv82KcrxSI4vbaipnFqc4D9dTYU) ![image](https://private-user-images.githubusercontent.com/22283930/343681270-a6bfc0d3-bd48-4762-8dab-58df45fd44af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjAwOTUsIm5iZiI6MTcyMDA1OTc5NSwicGF0aCI6Ii8yMjI4MzkzMC8zNDM2ODEyNzAtYTZiZmMwZDMtYmQ0OC00NzYyLThkYWItNThkZjQ1ZmQ0NGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YjJlMTdjMjg5N2M0OGJiN2ZhNTE0MDExZjE3Mzk1NDdmYzU4MzlhOTQ4Y2ZlYmY1MmNjMmExNTFiY2Q5NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VnHWg1xcbyORxl_JFscWaebAlrorGxtSoyYHFadaqY) ![image](https://private-user-images.githubusercontent.com/22283930/343681086-29694528-c5cd-47b0-9d32-a6f9e792770f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjAwOTUsIm5iZiI6MTcyMDA1OTc5NSwicGF0aCI6Ii8yMjI4MzkzMC8zNDM2ODEwODYtMjk2OTQ1MjgtYzVjZC00N2IwLTlkMzItYTZmOWU3OTI3NzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDZhNDc5NjAwNTRhNmFkOWU2OGZkZDZmMjY4N2IyYTgzMmY1OTZhMmYyY2MzZDUyNDZmN2M4M2YzMWVjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Vax8n_qzjaaXVOenWaZuIDNqL4c93BY6-pwTuwkaN4)

ddl

```sql
CREATE TABLE `eq_user`  (
  `user_id` int NOT NULL,
  `open_id` varchar(255) NULL,
  `nickName` varchar(255) NULL,
  `avatarUrl` varchar(255) NULL,
  `gender` varchar(255) NULL,
  `country` varchar(255) NULL,
  `province` varchar(255) NULL,
  `city` varchar(255) NULL,
  `push_uid` varchar(255) NULL,
  PRIMARY KEY (`user_id`)
);
```

我测试了是没问题的，请自行检查下你当前的用户密码是否能执行这个sql获取数据表的列信息。

```sql
select `column_key` as `column_key`, `column_name` as `column_name`, `data_type` as `data_type`, `is_nullable` as `is_nullable`, `column_comment` as `column_comment`, `extra` as `extra`, `column_type` as `column_type` from information_schema.columns where `table_schema` = 'employees' and `table_name` = 'eq_user' order by ORDINAL_POSITION
```

```bash
php easyswoole.php model gen -table=employees -with-comments
```

生成结果：
```php
<?php

declare(strict_types=1);

namespace App\Model;

use EasySwoole\FastDb\AbstractInterface\AbstractEntity;
use EasySwoole\FastDb\Attributes\Property;

/**
 * @property int $emp_no 
 * @property string $birth_date 
 * @property string $first_name 
 * @property string $last_name 
 * @property string $gender 
 * @property string $hire_date 
 */
class Employees extends AbstractEntity
{
    #[Property(isPrimaryKey: true)]
    public int $emp_no;
    #[Property]
    public string $birth_date;
    #[Property]
    public string $first_name;
    #[Property]
    public string $last_name;
    #[Property]
    public string $gender;
    #[Property]
    public string $hire_date;

    public function tableName(): string
    {
        return 'employees';
    }
}
```
